### PR TITLE
Fetch user info

### PR DESCRIPTION
**Pull request by ChrisBr**

### CODE REVIEW

**Comment by ChrisBr** [comment]
Thanks for the quick merge @Eric-Guo

**Comment by Eric-Guo** [comment]
Thank you for contribution, will testing first and if no problem will do a release in 2 days and have a nice weekend.

**Comment by ChrisBr** [comment]
Thanks 👍 

I will prepare a PR to remove the logging again, it was just intended for debugging, sorry about that. I think we should not log the access token in production.

Also I was wondering if we should change to use the union id instead of the open id as uid.

> OpenID is an unique encrypted WeChat ID for each user of an OA (including Mini Program). Users have separate OpenIDs corresponding to different OAs. In Developer Mode, when subscribed users interact with an OA, the developer can obtain their OpenIDs and use it to get basic user information (gender, photo, location etc.)

> UnionID is an unique ID to identify a single user under the same WeChat open platform account. If a developer possesses multiple mobile applications, website applications, and OAs (including Mini Programs), they can use a UnionID to differentiate the uniqueness of users. In other words, UnionID offers a mechanism for developers to acquire a user’s data from multiple platforms and attribute actions back to the specific user.

Unlike the open id, the union id is stable. In our use case for instance, we have different WeChat applications for web, android and iOS but if you register on iOS you should also be able to login on web or android. I think this is the case for most users of this gem. Would you be open for a change too?

https://wiredcraft.com/blog/wechat-for-dummies-user-data-and-authorization/
https://stackoverflow.com/questions/40044572/wechat-open-platform-openid-and-unionid

**Comment by ChrisBr** [comment]
Remove logging https://github.com/NeverMin/omniauth-wechat-oauth2/pull/28.

The only problem with the OpenId -> UnionId change might be backward compatibility 🤔

**Comment by Eric-Guo** [comment]
Sorry, I just only have a quick glance instead of reading it, although I already read it this morning.

I'm OK to use the union id, but I guess not every WeChat program needs union id (at least I have one at hand no union id yet), anyway, I agree every WeChat program will eventually reach to using the union id at some point.

You can continue to propose PR and ping me if you believe it's ready, thanks again!

**Pull request merged**
